htmx_basic/urls.py
from django.urls import path

from . import views

app_name = 'htmx_basic'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('get-length/', views.get_name_length, name='get_name_length'),

]

todolist/urls.py
from django.urls import path
from .views import (
    TodoListView,
    TodoDeleteView,
    TodoCreateModalView,
    TodoUpdateModalView,
    TodoDetailModalView,
)

app_name = 'todolist'

urlpatterns = [
    path('', TodoListView.as_view(), name='todo_list'),
    path('novo/modal/', TodoCreateModalView.as_view(), name='todo_create_modal'),
    path('<int:pk>/modal/', TodoDetailModalView.as_view(), name='todo_detail_modal'),
    path('<int:pk>/editar/modal/', TodoUpdateModalView.as_view(), name='todo_update_modal'),
    path('<int:pk>/excluir/', TodoDeleteView.as_view(), name='todo_delete'),
]

htmx_basic/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(default=None, blank=True, null=True)
    featured_image = models.ImageField(
        upload_to='images/%Y/%m/%d/', default=None, blank=True, null=True)

htmx_basic/forms.py
from django import forms

from .models import Product


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'featured_image']

htmx_basic/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

from htmx_basic.forms import ProductCreateForm


class IndexView(TemplateView):
    template_name = 'htmx_basic/index.html'


class ProductCreateView(FormView):
    form_class = ProductCreateForm
    template_name = 'htmx_basic/product_edit.html'
    success_url = reverse_lazy('htmx_basic:index')

    def form_valid(self, form):
        form.save()  # save the product
        return super().form_valid(form)


def get_name_length(request):
    name = request.POST.get('name')
    length = str(len(name)) if len(name) > 0 else ''
    return HttpResponse(length)

htmx_basic/templates/htmx_basic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTMX Basic</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom CSS -->

    <!-- jQuery and Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

htmx_basic/templates/htmx_basic/index.html
{% extends 'htmx_basic/base.html' %}

{% block content %}

<div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Basic Sample</p>
    <hr/>
    <ul>
      <li><a href="{% url 'htmx_basic:create' %}">Get name length during product name input</a></li>
    </ul>
</div>

{% endblock content %}

htmx_basic/templates/htmx_basic/product_edit.html
{% extends 'htmx_basic/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Product Create</p>
    <hr/>
    <p>This sample show how to count the length of the field name as the user enter letters. Of course this could
    be resolved of client side. But the objective here registre how the HTMX function works at basic level.</p>
    <hr/>

    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label_tag }}</label>
        {{ form.name.errors }}
        <!--
        It's necessary save the url on a variable in order to pass the parameter to render_field custom tag. As try
        to call url tag directly on hx-post will cause a failure.
        -->
        {% url 'htmx_basic:get_name_length' as lenght_url %}
        {% render_field form.name class="form-control" hx-post=lenght_url hx-trigger="keyup changed" hx-target="#name-length-count" %}
        <div id="name-length-count"></div>
      </div>
      <div class="mb-3">
        <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label_tag }}</label>
        {{ form.description.errors }}
        {% render_field form.description class="form-control"  %}
      </div>
      <div class="mb-3">
        <label for="{{ form.featured_image.id_for_label }}" class="form-label">{{ form.featured_image.label_tag }}</label>
        {{ form.featured_image.errors }}
        {% render_field form.featured_image class="form-control"  %}
      </div>

      <button type="submit" class="btn btn-success mt-2">Register</button>
    </form>
</div>
{% endblock content %}